# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "GitHub Actions:"
    schedule:
      interval: "weekly"
      time: "02:00"
    groups:
      gh-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "swift"
    directory: "/"
    allow:
      - dependency-type: all
    commit-message:
      prefix: "Swift:"
    schedule:
      interval: "daily"
      time: "02:00"
    groups:
      swift-dependencies:
        patterns:
          - "*"
